version: '3'
services:
  devops:
    image: ramu478/aws
    ports:
      - "80:80"
    deploy:
      replicas: 3

  aws:
    image: ramu478/devops
    ports:
      - "81:80"
    deploy:
      replicas: 3

  datascience:
    image: ramu478/java
    ports:
      - "82:80"
    deploy:
      replicas: 3

  azure:
    image: ramu478/phython
    ports:
      - "83:80"
    deploy:
      replicas: 3
